### ISSUE TITLE
[FEAT] User 정보 조회 API

### ISSUE THREAD

**Issue by gitseoyeon** [Trip-Record/Server#19]
## Description
User 정보 관련 API
## To-Do
- [x] 다녀온 여행지 수
- [x] 추천 받은 개수
- [x] 유저 회원가입 정보
- [x] 유저 기록 개수
- [x] 유저 일정 개수
