### ISSUE TITLE
[FEAT] 기록을 수정하는 API

### ISSUE THREAD

**Issue by muncool39** [Trip-Record/Server#30]
## Description
기록을 수정하는 API 구현
- PATCH /records/{recordId} 

## To-Do
- [x] 기록 제목 및 내용 수정
- [x] 기록에 포함되는 여행지 수정
- [x] 기록에 포함되는 이미지 추가 및 삭제
