### ISSUE TITLE
[FEAT] 여행 스타일 목록 조회 API

### ISSUE THREAD

**Issue by gitseoyeon** [Trip-Record/Server#47]
## Description
DB에 등록된 여행 스타일 목록을 불러오는 API
## To-Do
- [x] TripStyleController 생성 및 구현
- [x] TripStyleService 생성 및 구현
- [x] TripStyle DTO 생성 및 구현
