### ISSUE TITLE
[FEAT] 기록에 댓글을 생성하는 API

### ISSUE THREAD

**Issue by muncool39** [Trip-Record/Server#67]
## Description
기록에 댓글을 생성하는 API 개발
POST /records/{recordId}/comments

## To-Do
- [x] request dto 생성
- [x] dto 객체 검증
- [x] DB 적용 확인

## Reference
